housedata=read.csv(file.choose(),sep = ',',header = T,stringsAsFactors = F)
View(housedata)
View(housedata)
summary(housedata)
str(housedata)
nrow(housedata)
dim(housedata)
library(ggplot2)
library(ggplot)
library(tidyverse)
hist(housedata$Home.Value)
ggplot(housedata,aes(x=Home.Value,color='green'))+geom_histogram()
ggplot(filter(housedata,State%in%c("MA","TX")),aes(x=Date,y=Home.Value,color=State))+geom_point()
ggplot(housedata,aes(x=log(Land.Value),y=Structure.Cost))+geom_text(aes(label=State),size=3)
ggplot(filter(housedata,State%in%c("MA","TX")),aes(x=Date,y=Home.Value,color=State))+geom_bar(stat = "identity")
