fruits=c(rep('male',20),rep('female',10))
print(fruits)
print(fruits[1:4])
fruits_apple=c("Grapes","Apple","Mangoes")
print(fruits_apple)
itreation=c(rep("Male",45),rep("Female",78))
print(itreation)

factorcreate=factor(itreation)
print(factorcreate)
print(nlevels(factorcreate))
View(mtcars)
mtcarsworking=mtcars
mtcars$am
am
attach(mtcarsworking)
am
summary(fruits)
summary(mtcars)
